### ISSUE TITLE
Issues with class item sheet, equipment groups

### ISSUE THREAD

**Issue by Wigginns** [hitcherland/FoundryVTT-Heart#44]
When setting up Equipment Groups items dragged and dropped into the equipment area will always drop into the primary (solid lined) equipment group.

In addition, empty equipment groups cannot be deleted. The console gives an error, though in its minified form I'm afraid it's not too informative: 

``` 
heart.js:1 Uncaught (in promise) TypeError: undefined. this.deleteChildren is not a function
[Detected 1 package: system:heart]
    at HTMLAnchorElement.<anonymous> (heart.js:1:113324)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
(anonymous) @ heart.js:1
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Comment by Wigginns** [comment]
Turns out this isn't that big a deal if I use the pre-configured stuff in the compendiums. Still may be worth addressing but it isn't as big a hitch for me running a game at the moment :)

**Comment by Wigginns** [comment]
Will be fixed in https://github.com/Wigginns/FoundryVTT-Heart/pull/9
